version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nestjs_app

  nestjs_app:
    build:
      context: .
      dockerfile: Dockerfile  # Path to your NestJS Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongodb  # Assuming you have a MongoDB service defined

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27018"
